trigger:
  branches:
    include:
      - main

variables:
  watchtower: xxx
  docker_hub: xxx
  TURBO_TOKEN: xxx
  TURBO_TEAM: xxx
  NEXT_TELEMETRY_DISABLED: 1
  TURBO_TELEMETRY_DISABLED: 1
  
  DEVOPS_ORG: xxx
  DEVOPS_PROJECT: xxx
  DEVOPS_BUILD_DEF_ID: xxx

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: "0"

  - task: Bash@3
    displayName: "Get latest successful build"
    inputs:
      targetType: "inline"
      script: |
        echo "Getting latest successful build..."

        # API-URL für den letzten erfolgreichen Build
        uri="https://dev.azure.com/$(DEVOPS_ORG)/$(DEVOPS_PROJECT)/_apis/build/builds?definitions=$(DEVOPS_BUILD_DEF_ID)&resultFilter=succeeded&statusFilter=completed&maxBuildsPerDefinition=1&queryOrder=finishTimeDescending&api-version=6.0"
        echo $uri

        # API-Aufruf mit curl und dem System Access Token
        response=$(curl -s -H "Authorization: Bearer $(System.AccessToken)" "$uri")

        # Prüfen, ob die Anfrage erfolgreich war
        if [[ $response == *"value"* ]]; then
          # Extrahieren des letzten Builds aus der JSON-Antwort (benötigt jq)
          latestBuild=$(echo $response | jq '.value[0]')
          
          # Extrahieren der Commit-ID
          commitId=$(echo $latestBuild | jq -r '.sourceVersion')
          echo "Commit-SHA: $commitId"
          
          # Variable für Azure DevOps Pipeline setzen
          echo "##vso[task.setvariable variable=BASE_SHA]$commitId"
        else
          echo "Fehler beim Abrufen des letzten Builds: $response"
          exit 1
        fi
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - script: |
      echo "Docker Login"
      echo "$(docker_hub)" | docker login --username tobiasbenkner --password-stdin
      npm i -g pnpm
    displayName: "Config"

  - script: |
      pnpm i
    displayName: "Dependencies"

  - script: |
      npx turbo run build --filter=...[$(BASE_SHA)] --continue=always
    displayName: "Build"
    env:
      TURBO_TOKEN: $(TURBO_TOKEN)
      TURBO_TEAM: $(TURBO_TEAM)
      NEXT_TELEMETRY_DISABLED: 1
      TURBO_TELEMETRY_DISABLED: 1

  - script: |
      npx turbo run docker:build --filter=...[$(BASE_SHA)]
    displayName: "Docker Build"
    env:
      TURBO_TOKEN: $(TURBO_TOKEN)
      TURBO_TEAM: $(TURBO_TEAM)
      NEXT_TELEMETRY_DISABLED: 1
      TURBO_TELEMETRY_DISABLED: 1

  - script: |
      npx turbo run docker:push --filter=...[$(BASE_SHA)]
    displayName: "Docker Push"
    env:
      TURBO_TOKEN: $(TURBO_TOKEN)
      TURBO_TEAM: $(TURBO_TEAM)
      NEXT_TELEMETRY_DISABLED: 1
      TURBO_TELEMETRY_DISABLED: 1

  - script: |
      curl -H "Authorization: Bearer $(watchtower)" https://baile-update.pulpo.cloud/v1/update
    displayName: "Deploy"
