networks:
  traefik:
    external: true
    
services:
  traefik:
    image: traefik:v3.4
    restart: always
    command:
      - "--entrypoints.cloudflare.address=:8080"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      
      - "--certificatesresolvers.vault.acme.caServer=http://vault:8200/v1/pki_int/acme/directory"
      - "--certificatesresolvers.vault.acme.email=info@benkner-it.com"
      - "--certificatesresolvers.vault.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.vault.acme.httpchallenge.entrypoint=web"

      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=info@benkner-it.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/letsencrypt.json"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme:/acme"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik

