services:
  checkmk:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk
    restart: always
    ports:
      - 8080:5000
      - 6556:6556
    volumes:
      - /opt/checkmk/data:/opt/omd/sites
